steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Building AI Agent Generator Backend..."
    ls -la
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-generator-backend', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ai-generator-backend']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'ai-generator-backend'
  - '--image'
  - 'gcr.io/$PROJECT_ID/ai-generator-backend'
  - '--region'
  - 'southamerica-east1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '2Gi'
  - '--cpu'
  - '2'
  - '--timeout'
  - '900'
  - '--max-instances'
  - '10'
  - '--concurrency'
  - '100'
images:
- 'gcr.io/$PROJECT_ID/ai-generator-backend'
